"""Initial migration with User model

Revision ID: 4233dc320fd0
Revises: 
Create Date: 2026-01-20 22:25:31.450628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4233dc320fd0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allowance_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('is_taxable', sa.Boolean(), nullable=True),
    sa.Column('is_includable_in_minimum_wage', sa.Boolean(), nullable=True),
    sa.Column('is_fixed', sa.Boolean(), nullable=True),
    sa.Column('is_included_in_regular_wage', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allowance_templates_id'), 'allowance_templates', ['id'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('dependents_count', sa.Integer(), nullable=True),
    sa.Column('children_under_20', sa.Integer(), nullable=True),
    sa.Column('employment_type', sa.String(length=20), nullable=True),
    sa.Column('company_size', sa.String(length=20), nullable=True),
    sa.Column('scheduled_work_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_index(op.f('ix_employees_user_id'), 'employees', ['user_id'], unique=False)
    op.create_table('salary_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('base_salary', sa.Integer(), nullable=False),
    sa.Column('allowances_json', sa.Text(), nullable=True),
    sa.Column('total_gross', sa.Integer(), nullable=True),
    sa.Column('total_deductions', sa.Integer(), nullable=True),
    sa.Column('net_pay', sa.Integer(), nullable=True),
    sa.Column('calculation_detail', sa.Text(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_records_id'), 'salary_records', ['id'], unique=False)
    op.create_index(op.f('ix_salary_records_user_id'), 'salary_records', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_salary_records_user_id'), table_name='salary_records')
    op.drop_index(op.f('ix_salary_records_id'), table_name='salary_records')
    op.drop_table('salary_records')
    op.drop_index(op.f('ix_employees_user_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_allowance_templates_id'), table_name='allowance_templates')
    op.drop_table('allowance_templates')
    # ### end Alembic commands ###
